### ISSUE TITLE
Python 3.12 config parser error

### ISSUE THREAD

**Issue by ece-mohammad** [mattrobenolt/jinja2-cli#119]
## Error:

- **Python version**: 3.12

```
Traceback (most recent call last):
  File "/home/pegasus/.pyenv/versions/jinja2-3.12/bin/jinja2", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pegasus/Projects/jinja2cli/jinja2cli/cli.py", line 476, in main
    sys.exit(cli(opts, args))
             ^^^^^^^^^^^^^^^
  File "/home/pegasus/Projects/jinja2cli/jinja2cli/cli.py", line 330, in cli
    data = fn(data) or {}
           ^^^^^^^^
  File "/home/pegasus/Projects/jinja2cli/jinja2cli/cli.py", line 134, in _parse_ini
    p.readfp(StringIO(data))
    ^^^^^^^^
AttributeError: 'MyConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
```

## Reproduction steps:

1. Install jinja2-cli in a virtualenv
```text
gh repo clone mattrobenolt/jinja2-cli jinja2cli && cd jinja2cli
python -m virtualen .venv
source .venv/bin/activate
pip install -e .
```

2. create a `ini` data file and a template:
  - `data.ini` file:
```
[data]
foo=bar
ham=spam
```

  - `template.j2` file:
```rbe
## Data:

- foo: {{ data.foo }}
- bar: {{ data.bar }}
```

3. run the commands:
```text
jinja2 ./data.ini ./template.j2
```

According to Python 3.12 documentation, [`ConfigParser.read_file`](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read_file) replaced `ConfiggParser.readfp()`, and `ConfigParser.readfp()` is no longer recognized.

**Comment by mattrobenolt** [comment]
Fixed with 38b9b9e5f1b8a0625aedaa3ae6b324b442390f04
