### ISSUE TITLE
Not working on Python 3.12 - ModuleNotFoundError: No module named 'imp'

### ISSUE THREAD

**Issue by dovi-klausner** [mattrobenolt/jinja2-cli#127]
Hello.
This is the issue:
```bash
ubuntu@ip-172-31-31-127:~$ j2
Traceback (most recent call last):
  File "/home/ubuntu/sisense-develop.14418/sisense-installer/bin/j2", line 5, in <module>
    from j2cli import main
  File "/home/ubuntu/sisense-develop.14418/sisense-installer/lib/python3.12/site-packages/j2cli/__init__.py", line 10, in <module>
    from j2cli.cli import main
  File "/home/ubuntu/sisense-develop.14418/sisense-installer/lib/python3.12/site-packages/j2cli/cli.py", line 8, in <module>
    import imp, inspect
ModuleNotFoundError: No module named 'imp'

ubuntu@ip-172-31-31-127:~$ python -V
Python 3.12.3
```
Any chance this can be fixed so it won't use this module `imp`?
I understood that this module isn't working on Python 3.12
(maybe I'm wrong or it'll be fixed, but you should check on that)

Thanks in advance :)

**Comment by mattrobenolt** [comment]
TIL, I'll figure out the workaround for 3.12. I'm mildly in the process of a refresh of the codebase to modernize on python 3 only and whatnot, so I'll tackle this as well.

**Comment by mattrobenolt** [comment]
Oh, that's from a different package, not this package. Seems to be from https://github.com/kolypto/j2cli
