### ISSUE TITLE
I cannot work out what is wrong with this

### ISSUE THREAD

**Issue by Lucretia** [mattrobenolt/jinja2-cli#133]
test.ads.jinja

```jinja
{% import 'packages.ada.jinja' as packages %}

{{ packages.package_spec('Test') }}

{{ test }} {# This works #}
```

packages.ada.jinja

```jinja
{% import "comments.ada.jinja" as comments %}

{% macro package_spec(package_name) -%}
{{ comments.package_header() }}

package {{ package_name }} is
   {{ test }} {# This does NOT work! #}
end {{ package_name }};
{%- endmacro %}
```

comments.ada.jinja

```jinja
{% macro package_header() %}
--  This package is distributed under the BSD-2 licence.
--
--  This package was auto-matically generated, do not edit by hand.
{% endmacro %}
```

data.yaml

```yaml
test: "--  TODO:"
```

Output

```bash
$ jinja2 --strict src/templates/test.ads.jinja data.yaml  --format=yaml
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/jinja2", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/jinja2cli/cli.py", line 449, in main
    sys.exit(cli(opts, args))
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jinja2cli/cli.py", line 339, in cli
    out.write(render(template_path, data, extensions, opts.strict))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jinja2cli/cli.py", line 254, in render
    return env.get_template(os.path.basename(template_path)).render(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/usr/lib/python3.12/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/laguest/src/binding-gen/chimera/thirdparty/testj/src/templates/test.ads.jinja", line 3, in top-level template code
    {{ packages.package_spec('Test') }}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jinja2/runtime.py", line 782, in _invoke
    rv = self._func(*arguments)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laguest/src/binding-gen/chimera/thirdparty/testj/src/templates/packages.ada.jinja", line 7, in template
    {{ test }} {# This does NOT work! #}
 ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.UndefinedError: 'test' is undefined
```

**Comment by Lucretia** [comment]
Seems it was this, https://jinja.palletsprojects.com/en/stable/templates/#import-context-behavior, which should be mentioned in the macros section as you might not see it, like I didn't.
