### ISSUE TITLE
UTF8 - IO Encoding

### ISSUE THREAD

**Issue by JackLeo** [mattrobenolt/jinja2-cli#48]
This is a bit of a weird one since it's a general python problem, but it also affects this tool.

```
$ echo "øl"
øl
$ echo "øl" > test
$ jinja2 test 
øl
$ jinja2 test > test2
Traceback (most recent call last):
  File "/bin/jinja2", line 11, in <module>
    load_entry_point('jinja2-cli==0.7.0', 'console_scripts', 'jinja2')()
  File "/usr/lib/python2.7/site-packages/jinja2cli/cli.py", line 364, in main
    sys.exit(cli(opts, args))
  File "/usr/lib/python2.7/site-packages/jinja2cli/cli.py", line 290, in cli
    sys.stdout.write(output)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 0: ordinal not in range(128)
```

and workaround this is

```
$ export PYTHONIOENCODING=utf-8
$ jinja2 test > test2
$ cat test2
øl
```

This is explored here https://stackoverflow.com/q/1473577/558194

So, to be a general Unix tool this should ideally support UTF-8, thus I would suggest implementing something to address potential issues.

**Comment by mattrobenolt** [comment]
Thanks for the report, I had some logic backwards. :)
