### ISSUE TITLE
Failure on python3.5

### ISSUE THREAD

**Issue by oz123** [mattrobenolt/jinja2-cli#53]
```
$ jinja2 sample.jinja2 sample.json 
Traceback (most recent call last):
  File "/home/otiram/.local/share/virtualenvs/jinja2-cli-42CEN4Q4/bin/jinja2", line 11, in <module>
    load_entry_point('jinja2-cli', 'console_scripts', 'jinja2')()
  File "/home/otiram/Software/jinja2-cli/jinja2cli/cli.py", line 364, in main
    sys.exit(cli(opts, args))
  File "/home/otiram/Software/jinja2-cli/jinja2cli/cli.py", line 290, in cli
    sys.stdout.write(output)
TypeError: write() argument must be str, not bytes
(jinja2-cli-42CEN4Q4) otiram@yoni ~/Software/jinja2-cli/samples $ python --version
Python 3.5.5
(jinja2-cli-42CEN4Q4) otiram@yoni ~/Software/jinja2-cli/samples $ 
```

**Comment by mattrobenolt** [comment]
This should be fixed with abb21e445050cd23dbcdb034deabee47ae1991b1

Let me know if you have an issue still.
