### ISSUE TITLE
Jinja2-cli incompatible with PyYAML 6.0

### ISSUE THREAD

**Issue by hans2520** [mattrobenolt/jinja2-cli#97]
TypeError: load() missing 1 required positional argument: 'Loader'

```
Traceback (most recent call last):
  File "/home/ubuntu/.tox/unit/bin/jinja2", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/.tox/unit/lib/python3.6/site-packages/jinja2cli/cli.py", line 424, in main
    sys.exit(cli(opts, args))
  File "/home/ubuntu/.tox/unit/lib/python3.6/site-packages/jinja2cli/cli.py", line 279, in cli
    data = fn(data) or {}
TypeError: load() missing 1 required positional argument: 'Loader'
```

A solution may be to use yaml.safe_load instead (e.g. on line 135 of cli.py): 
```
    return yaml.safe_load, yaml.YAMLError, MalformedYAML
```

Else the Loader argument will need to be provided.

**Comment by lhriley** [comment]
It looks like this issue has been solved in https://github.com/mattrobenolt/jinja2-cli/pull/96 but has not yet been released.

@mattrobenolt can you please push out a release with this fix?

**Comment by FOTempel** [comment]
@mattrobenolt Please?

**Comment by FOTempel** [comment]
@mattrobenolt Pretty please?

**Comment by mattrobenolt** [comment]
Ok ok, lemme try and figure out how to cut a new release today. I haven't even written Python in a while.

fwiw the best solution for this is to just install from source, which is how I've used this personally for years, which is why I never cut releases.

But gotta remember how python packaging works.

**Comment by FOTempel** [comment]
> Ok ok, lemme try and figure out how to cut a new release today. I haven't even written Python in a while.
> 
> fwiw the best solution for this is to just install from source, which is how I've used this personally for years, which is why I never cut releases.
> 
> But gotta remember how python packaging works.

Thanks, it worked out as I can now do a pip install of 0.8.0 which was the goal! Installing from source is fine for some cases I guess, but sometimes you just don't want the headache and pull something from a repository. It's what they're invented for.
