### ISSUE TITLE
Using jinja2-cli To Produce .py Files Produces A Stack Trace.

### ISSUE THREAD

**Issue by rawrgulmuffins** [mattrobenolt/jinja2-cli#98]
# Description
Tried to run a template with only one variable {{carrier} to produce a python file. This produced this stack trace.

```
(data_platform) alexlordthorsen@Alexs-MBP ~/git/data/data-platform/dags/dags/reconciliation/carrier_configs [1] :( % jinja2 config_template.jinja "fedex.py" -D carrier=fedex
Traceback (most recent call last):
  File "/Users/alexlordthorsen/.venvs/data_platform/bin/jinja2", line 8, in <module>
    sys.exit(main())
  File "/Users/alexlordthorsen/.venvs/data_platform/lib/python3.8/site-packages/jinja2cli/cli.py", line 424, in main
    sys.exit(cli(opts, args))
  File "/Users/alexlordthorsen/.venvs/data_platform/lib/python3.8/site-packages/jinja2cli/cli.py", line 257, in cli
    if has_format(ext):
  File "/Users/alexlordthorsen/.venvs/data_platform/lib/python3.8/site-packages/jinja2cli/cli.py", line 81, in has_format
    get_format(fmt)
  File "/Users/alexlordthorsen/.venvs/data_platform/lib/python3.8/site-packages/jinja2cli/cli.py", line 74, in get_format
    return formats[fmt]()
KeyError: 'py'
```

# Versions
(data_platform) alexlordthorsen@Alexs-MBP ~/git/data/data-platform/dags/dags/reconciliation/carrier_configs :) % python --version
Python 3.8.2
(data_platform) alexlordthorsen@Alexs-MBP ~/git/data/data-platform/dags/dags/reconciliation/carrier_configs :) % pip list | grep jinja2-cli
jinja2-cli                      0.7.0

**Comment by mattrobenolt** [comment]
Right, you need to use it like:

```
jinja2 config_template.jinja -D carrier=fedex > fedex.py
```

It doesn't write to a file directly and doesn't accept it as an argument.

**Comment by rawrgulmuffins** [comment]
Maybe I closed this too soon but I did realize I read the docs incorrectly.

I think it would be nice to have the stack trace explain the error more but I don't think this is an actual bug. Also, that was a lighting fast response. 0.o

**Comment by mattrobenolt** [comment]
Yeah, that's fair, the error is misleading since it's trying to read the second argument as a data source, so it expects like, `data.json` and would load it as `JSON` format. In this case, it was like "I don't know what `.py` is for data.
